version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
